### ISSUE TITLE
Colors and Fonts

### ISSUE THREAD

**Issue by jcrimp** [jcrimp/openelis-itc210#24]
Fonts used: Aller and Aller Bold
Grid: 12 columns, 15px gutters. Total width: 1000px w/o exterior padding, 1015 with exterior padding.

Maddy provided colors, I will work on applying them tonight and tomorrow.

**Comment by madstash** [comment]
the grid I was able to work out is> 1000px, 12 columns, and 16px gutter.
The link below provides pixel widths that are helpful.

http://www.gridsystemgenerator.com/gs04.php?GridWidth=1000&GridColumns=12&GridMarginLeft=32

**Comment by jcrimp** [comment]
Cool, I can do 16px gutters easily. The columns work out to be 68.66666px wide, and for my grid calculations I add an additional 8px of padding to the outside edges, making the measure from edge to edge including the extra padding 1016px.

**Comment by madstash** [comment]
I'm not even sure if I'm doing these right. I've only worked with the
960-980 grid.The gutters seem huge to me, but the software was able to
calculate it, so I guess it works.

**Comment by jcrimp** [comment]
I think 16px is actually on the small side for gutters. That's what the "GUIDES 2" layer in your ai file is using, and I think it looks good. The link you provided above is totally different, and uses 32px gutters (which do look huge) but our design doesn't look to be using that grid at all, so I think we're good with the 16px gutters. I don't think we need to make any changes. 
The "GUIDES" layer looks to be using a 1366 grid, which is not necessary- that's just the max-width constraint we're using on anything not contained within the grid (spotlight image, header background color, footer background color, home page slider, and home page color blocks).

**Comment by madstash** [comment]
actually it's 16 on both sides equaling 32.

**Comment by madstash** [comment]
Jenny I hope you are not entirely set on that grid system... I'm going to
speak with people at work to see what the best build will be.

On Thu, Nov 19, 2015 at 9:05 AM, Madalena Homem <mhomem01@seattlecentral.edu

**Comment by madstash** [comment]
I think I'm going to revert back to 960 grid. I need to start the spec'ing
this out, so please let me know if you are ok with that.

Thanks!
Maddy

On Thu, Nov 19, 2015 at 9:18 AM, Madalena Homem <mhomem01@seattlecentral.edu
> wrote:

> Jenny I hope you are not entirely set on that grid system... I'm going to
> speak with people at work to see what the best build will be.
>
> On Thu, Nov 19, 2015 at 9:05 AM, Madalena Homem <

**Comment by jcrimp** [comment]
Yeah, I just sent you an email, and that works fine!
