### ISSUE TITLE
Get the favicon working

### ISSUE THREAD

**Issue by jcrimp** [jcrimp/openelis-itc210#31]

**Comment by jcrimp** [comment]
I found a really easy way to add a favicon through Wordpress- http://www.wpbeginner.com/wp-tutorials/how-to-add-a-favicon-to-your-wordpress-blog/

Maddy, can you make a square .png of the icon that is 512x512px (it can be larger, too)? If you get the chance, you can follow the instructions in the article above for Wordpress 4.3 and above.

Log in to the admin dashboard on the staging server, in the sidebar, select "Apperance > Customize". Then when it takes you to the site, click "Site Identity" from the sidebar there. Under "Site Icon" you can click "Select file", then click the upload tab to upload the icon to the media library. It requires you to crop it to a square, which is why the original .png should be square.

**Comment by madstash** [comment]
Got it. Thanks Jenny!

**Comment by jcrimp** [comment]
Thanks Maddy!
