### ISSUE TITLE
Confirm what contact information will be visible on the site

### ISSUE THREAD

**Issue by jcrimp** [jcrimp/openelis-itc210#6]

**Comment by madstash** [comment]
Maybe something like this?

**Comment by jcrimp** [comment]
The client said she wants to have people and emails listed on the Contact page, so the next step will be to add that sample content to the page, so we can then decide how to lay it out.

**Comment by flairli** [comment]
I can work on this task.

On Wednesday, November 18, 2015, Jenny Crimp <notifications@github.com>
wrote:

> The client said she wants to have people and emails listed on the Contact
> page, so the next step will be to add that sample content to the page, so
> we can then decide how to lay it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcrimp/openelis-itc210/issues/6#issuecomment-157915853>
> .
>


-- 
Sent from Gmail Mobile

**Comment by madstash** [comment]
Thanks Flair!

**Comment by jcrimp** [comment]
We're going with a contact form for general inquiries, and a list of contacts in the sidebar, with Title, name, and email for each person listed.
